import { Component, OnInit } from '@angular/core';
import {FormBuilder, FormGroup, Validators} from "@angular/forms";
import {ProductsService} from "../products.service";
import {Router} from "@angular/router";



@Component({
  selector: 'app-create-product',
  templateUrl: './create-product.component.html',
  styleUrls: ['./create-product.component.scss']
})
export class CreateProductComponent implements OnInit {
  productForm: FormGroup;
  ratings = [1, 2, 3, 4, 5];
  reviews = [0, 5, 10, 15, 20];
  availabilityOptions = ['Yes', 'No'];

  constructor(private fb: FormBuilder, private productService: ProductsService , private router: Router) {
    this.productForm = this.fb.group({
      productId: [''], // Optional if auto-generated by backend
      productName: ['', [Validators.required, Validators.minLength(3)]],
      categoryId: [null, Validators.required],
      color: ['', Validators.required],
      productPrice: [null, [Validators.required, Validators.min(1)]],
      rating: [null, Validators.required],
      isAvailable: ['Yes', Validators.required],
      reviews: [0, Validators.required],
      description: ['', Validators.maxLength(200)],
      productImg: ['']
    });
  }

  onSubmit() {
    if (this.productForm.valid) {
      const formData = {
        productId: this.productForm.get('productId').value,
        productName: this.productForm.get('productName').value,
        categoryId: +this.productForm.get('categoryId').value, // Ensure numeric
        description: this.productForm.get('description').value,
        rating: +this.productForm.get('rating').value,
        price: +this.productForm.get('productPrice').value,
        productImg: this.productForm.get('productImg').value,
        isAvailable: this.productForm.get('isAvailable').value === 'Yes',
        color: this.productForm.get('color').value,
        reviews: +this.productForm.get('reviews').value,
      };

      this.productService.createProduct(formData).subscribe(
        (data) => {
          console.log('Product added:', data);
          this.router.navigate([`/products`]);
        },
        (error) => {
          console.error('Error:', error);
        }
      );
    } else {
      console.log('Form is invalid');
    }
  }
  cancel() {
    this.router.navigate(['/products']);
  }
  ngOnInit(): void {
  }
}

